# Generated by Django 4.1.1 on 2022-09-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TelegramUser",
        ),
    ]
