# Generated by Django 4.1.1 on 2022-09-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_delete_telegramuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="max_price",
        ),
        migrations.RemoveField(
            model_name="event",
            name="min_price",
        ),
        migrations.AddField(
            model_name="event",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
