# Generated by Django 4.1.1 on 2022-09-10 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_event_max_price_remove_event_min_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="active",
        ),
        migrations.AddField(
            model_name="event",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
