# Generated by Django 4.1.1 on 2022-09-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_event_active_event_accepted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="accepted",
            field=models.BooleanField(default=False, verbose_name="Прошло модерацию"),
        ),
        migrations.AlterField(
            model_name="event",
            name="address",
            field=models.CharField(blank=True, max_length=200, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer",
            field=models.CharField(max_length=100, verbose_name="Организатор"),
        ),
        migrations.AlterField(
            model_name="event",
            name="price",
            field=models.IntegerField(default=0, verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="event",
            name="thumbnail",
            field=models.ImageField(
                blank=True, upload_to="events", verbose_name="Обложка"
            ),
        ),
    ]
