# Generated by Django 4.1.1 on 2022-09-10 21:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_event_accepted_alter_event_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="creator",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(verbose_name="Дата и время"),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="event",
            name="duration",
            field=models.DurationField(
                default=datetime.timedelta(seconds=3600), verbose_name="Длительность"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.IntegerField(
                choices=[
                    (0, "Ограниченная группа"),
                    (1, "Индивидуальное"),
                    (2, "Массовое"),
                ],
                default=0,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="max_members",
            field=models.IntegerField(default=30, verbose_name="Количество участников"),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="event",
            name="reg_needed",
            field=models.BooleanField(
                default=False, verbose_name="Требуется регистрация"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
        ),
    ]
