# Generated by Django 4.1.1 on 2022-09-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_event_creator_alter_event_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="date",
        ),
        migrations.AddField(
            model_name="event",
            name="end",
            field=models.DateTimeField(default=None, verbose_name="Окончание"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="start",
            field=models.DateTimeField(default=None, verbose_name="Начало"),
            preserve_default=False,
        ),
    ]
