# Generated by Django 4.1.1 on 2022-09-10 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_event_date_event_end_event_start"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="duration",
        ),
    ]
