# Generated by Django 4.1.1 on 2022-09-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_event_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="max_members",
            field=models.IntegerField(default=0, verbose_name="Количество участников"),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Организатор"
            ),
        ),
    ]
