# Generated by Django 4.1.1 on 2022-09-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_event_max_members_alter_event_organizer"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="starred_events",
            field=models.ManyToManyField(to="core.event"),
        ),
    ]
