# Generated by Django 4.1.1 on 2022-09-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_user_starred_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="verbose_address",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Краткий адрес"
            ),
        ),
    ]
