# Generated by Django 4.1.1 on 2022-09-11 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_event_verbose_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="max_members",
            new_name="participants",
        ),
        migrations.RemoveField(
            model_name="event",
            name="event_type",
        ),
    ]
