# Generated by Django 4.1.1 on 2022-09-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_rename_max_members_event_participants_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="slug",
        ),
        migrations.AlterField(
            model_name="event",
            name="participants",
            field=models.IntegerField(default=1, verbose_name="Количество участников"),
        ),
    ]
