# Generated by Django 4.1.1 on 2022-09-11 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_event_slug_alter_event_participants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="thumbnail",
        ),
    ]
