# Generated by Django 4.1.1 on 2022-09-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_event_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="max_price",
            field=models.IntegerField(
                default=None, null=True, verbose_name="Максимальная цена"
            ),
        ),
    ]
