# Generated by Django 4.1.1 on 2022-09-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_event_max_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="verbose_address",
        ),
    ]
