# Generated by Django 4.1.1 on 2022-09-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_remove_event_verbose_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="thumbnail",
            field=models.ImageField(
                blank=True, upload_to="events", verbose_name="Обложка"
            ),
        ),
    ]
